function [mm,prices] = errorFutures(pp,model,FuturesPrices,muf,vf,lambdaf)

switch model.name
  case 'SVJDILRL'
    model.setParameterValues('kappaxQ',exp(pp(1)), ...
                             'kappamuQ',exp(pp(2)), ...
                             'kappavQ',exp(pp(3)), ...
                             'nupQ',exp(pp(4)), ...
                             'nunQ',exp(pp(5)), ...
                             'nuvQ',exp(pp(6)), ...
                             'nulambdaQ',exp(pp(7)));
    
    model.updateFuturesPricingCoefficients();
    prices = model.getFuturesPrices(FuturesPrices,muf,vf,lambdaf)';
  case 'SVJLRL'
    model.setParameterValues('kappaxQ',exp(pp(1)), ...
                             'kappamuQ',exp(pp(2)), ...
                             'kappavQ',exp(pp(3)), ...
                             'nupQ',exp(pp(4)), ...
                             'nunQ',exp(pp(5)), ...
                             'nuvQ',exp(pp(6)));
    
    model.updateFuturesPricingCoefficients();    
    prices = model.getFuturesPrices(FuturesPrices,muf,vf)';
  case 'SVJDI'
    model.setParameterValues('kappaxQ',exp(pp(1)), ...
                             'kappavQ',exp(pp(2)), ...
                             'nupQ',exp(pp(3)), ...
                             'nunQ',exp(pp(4)), ...
                             'nuvQ',exp(pp(5)), ...
                             'nulambdaQ',exp(pp(6)));
    
    model.updateFuturesPricingCoefficients();    
    prices = model.getFuturesPrices(FuturesPrices,vf,lambdaf)';
  case 'SVJ'
    model.setParameterValues('kappaxQ',exp(pp(1)), ...
                             'kappavQ',exp(pp(2)), ...
                             'nupQ',exp(pp(3)), ...
                             'nunQ',exp(pp(4)), ...
                             'nuvQ',exp(pp(5)));
    
    model.updateFuturesPricingCoefficients();    
    prices = model.getFuturesPrices(FuturesPrices,vf)';
end

mm = sqrt(mean((log(FuturesPrices.Price) - log(prices)).^2));

end